import type { Metadata } from "next";
import { mouse_memoirs } from "./font";
import Head from "next/head";
import Link from "next/link";
import "./globals.css";


export const metadata: Metadata = {
  title: "Hangman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
      <link rel="shortcut icon" href="../public/icon.png"/>
      </Head>
      <body className={`${mouse_memoirs.className} antialiased`}>{children}</body>
    </html>
  );
}
